cv: 5
random_state: 42
n_jobs: 8
output_folder: '../mlp_exp'
model: 'mlp'
do_feature_selection: True
hyperparameters:
  hidden_layer_sizes: [50, 100]
  activation: ['tanh', 'relu']
  solver: ['adam']
  alpha: [0.1, 0.01]
  learning_rate: ['constant', 'adaptive']

preprocess:
  target_column: 'Label'
  normalizer: 'standard' #[standard, l1, l2, minmax, robust, null]
  drop_threshold: 0.2
  categorical_impute: 'external' # [most_frequent, external]
  real_impute: 'mean' # [iterative, mean, external]
  balancing_method: 'null' #[smote, weighted, null]
  
  min_features: 100
feature_selection_params:
  step: 5
  max_features: 120
  score_threshold: 0.70