cv: 5
random_state: 0
n_jobs: 8
output_folder: 'experiments'
model: 'randomforest'
do_feature_selection: False
hyperparameters:
  n_estimators: [25, 50, 100]
  max_features: ['sqrt']
  max_depth: [2, 5, 10, 20]
  min_samples_split: [2, 4, 10]
  min_samples_leaf: [1, 2, 4]

preprocess:
  target_column: 'Death'
  normalizer: 'standard' #[standard, l1, l2, minmax, robust, null]
  drop_threshold: 0.3
  categorical_impute: 'external'
  real_impute: 'iterative'
  balancing_method: 'smote' #[smote, weighted, null]
  
feature_selection_params:
  step: 2
  min_features: 8
  max_features: 20
  score_threshold: 0.95
