name: ml-pipeline
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.9.10
  - dill==0.3.4
  - imbalanced-learn==0.8.1
  - joblib==1.0.1
  - matplotlib==3.3.4
  - numba==0.53.1
  - numpy==1.20.3
  - pandas==1.3.2
  - pymongo==4.0
  - PyYAML==6.0
  - scipy==1.7.1
  - seaborn==0.11.1
  - statsmodels==0.12.2
  - scikit-learn==1.0.1
  - shap==0.39.0
  - pip
  - pip:
    - mrmr-selection==0.2.0
    - xgboost==1.6.2
